version: '3.9'

services:
  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.0-amd64
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - 15601:5601
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0-amd64
    environment:
      LICENSE: basic
      discovery.type: single-node
    ports:
      - 9200:9200
