# Use root/pass as user/password credentials
version: '3.1'

services:
  web:
    image: nginxinc/nginx-unprivileged:stable-alpine
    volumes:
#      - .\nginx.conf:/etc/nginx/conf.d/
      - .\html:/usr/share/nginx/html
    ports:
      - 80:8080