# Use root/pass as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:8.0.26
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - .\db-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 3001:8080